src = woarcassemble.c
obj = $(src:.c=.o)

LDFLAGS = 
CFLAGS = -g -I.
OUTNAME = libwoarc.a

$(OUTNAME): $(obj)
	ar rcs $(OUTNAME) $(obj)

.PHONY: clean
clean:
	rm -f $(obj) $(OUTNAME)

install: $(OUTNAME)
	cp woarcassemble.h /usr/local/include/
	cp woarcFormatInfo.h /usr/local/include/
	cp $(OUTNAME) /usr/local/lib/
	@echo installed
